Save failed replay And Fixed a bug
osudroid/osu-droid pull request #102
Opened 2021-03-19 14:45 UTC by None1637

Can save failed replay
Can save replay in offline
Fixed a bug that star calculate no calculate DT/NC/speed modify
move the pp display (score scene) to left-bottom

2021-03-19 14:54 UTC, Rian8337 commented
The star rating calculation bug has actually been fixed, but it's up to you if you want to revert the change related to it or not. It should be fine this way as well.

2021-03-20 04:01 UTC, Rian8337 requested changes

2021-03-20 10:34 UTC, None1637 commented on src/ru/nsu/ccfit/zuev/osu/helper/DifficultyReCalculator.java
> +        if (!init(track)) {
ok, I will fixed this problem

2021-03-21 04:48 UTC, Rian8337 commented
After testing in-game, I have two concerns:
- In replay, sliders occasionally gives 100 despite not being pressed. The video below should show it (bad audio, but the point is still there).
https://user-images.githubusercontent.com/52914632/111894058-3103c900-8a3a-11eb-8995-6d478fe31a14.mp4
- Every hitobject that appears/should appear after the play fails is counted as miss, which is not something that we want? Unless this is required to tackle possible replay bug.

2021-03-21 04:49 UTC, Rian8337 approved these changes

2021-03-21 04:50 UTC, Rian8337 commented
Just need answers for my questions.

2021-03-21 13:13 UTC, None1637 commented
> 
> 
> After testing in-game, I have two concerns:
> 
>     * In replay, sliders occasionally gives 100 despite not being pressed. The video below should show it (bad audio, but the point is still there).
>       https://user-images.githubusercontent.com/52914632/111894058-3103c900-8a3a-11eb-8995-6d478fe31a14.mp4
> 
>     * Every hitobject that appears/should appear after the play fails is counted as miss, which is not something that we want? Unless this is required to tackle possible replay bug.

In replay, sliders occasionally gives 100 despite not being pressed.
 -This is a bug. I think that's why replay can get higher combo than real play. Maybe I can fix this bug.
Every hitobject that appears/should appear after the play fails is counted as miss, which is not something that we want? Unless this is required to tackle possible replay bug.
 -If don't counted as miss, Every hitobject that appears/should appear after the play fails will be hit automatically in the replay. Count them as miss is the easiest way to solve this problem.

2021-03-22 05:05 UTC, Rian8337 commented
> This is a bug. I think that's why replay can get higher combo than real play. Maybe I can fix this bug.

Isn't that the original replay bug, which is caused by movement emulation?

> If don't counted as miss, Every hitobject that appears/should appear after the play fails will be hit automatically in the replay. Count them as miss is the easiest way to solve this problem.

The play would have failed already, so it shouldn't matter?

2021-03-22 10:18 UTC, None1637 commented
> Isn't that the original replay bug, which is caused by movement emulation? This one seems different since no cursor is present.

the original replay bug Include this bug.

> The play would have failed already, so it shouldn't matter? I reckon this had something to do with the bug we've discussed earlier.

It does have something to do with bugs, and If don't count as miss, the replay would not fail.

2021-03-26 03:13 UTC, NeroYuki commented
i assume this can show off the bug better https://www.youtube.com/watch?v=0lfl53hofEQ (skip to 0:15)

2021-03-28 20:21 UTC, None1637 commented
> 
> 
> i assume this can show off the bug better https://www.youtube.com/watch?v=0lfl53hofEQ (skip to 0:15)

this bug is fixed in my previous [commit](https://github.com/osudroid/osu-droid/pull/102/commits/1914f4d60781834fe55500b2e93b44fe6c622434)

2021-04-13 14:06 UTC, merged