Implement input block area to prevent accidental touch
osudroid/osu-droid pull request #398
Opened 2024-08-23 21:36 UTC by Reco1I

* Supersedes #350

2024-08-26 02:11 UTC, Rian8337 commented on res/values/strings.xml
> +	<string name="block_area_preference_summary">Add, remove, and resize input block areas</string>
```suggestion
<string name="block_area_preference_title">Manage input block areas</string>
	<string name="block_area_preference_summary">Manage specific areas within the screen where presses will be ignored during gameplay</string>
```
Maybe? The current description does not explain what an "input block area" does.

2024-08-29 00:14 UTC, Rian8337 requested changes

2024-08-29 00:14 UTC, Rian8337 commented on src/ru/nsu/ccfit/zuev/osu/MainScene.java
> +        Config.loadOnlineConfig();
Test failure:
```suggestion
        Config.loadOnlineConfig(context);
```

2024-08-29 00:39 UTC, Reco1I commented on src/ru/nsu/ccfit/zuev/osu/MainScene.java
> +        Config.loadOnlineConfig();
Solved

2024-08-29 00:46 UTC, merged