Add Hide UI option during gameplay
osudroid/osu-droid pull request #92
Opened 2021-02-13 06:07 UTC by giang428

adding an option to hide score text, combo text, accuracy text and health bar during gameplay

2021-02-13 08:00 UTC, Rian8337 commented
There are so many unnecessary changes here. Please only change/add what is needed to achieve what you want.

And in best practice, you should name your commit properly so that it is easier to identify what your commit does without having to inspect the changes.

2021-02-13 08:09 UTC, Rian8337 commented on AndEngine/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.2'
Are these changes to gradle necessary?

2021-02-13 10:10 UTC, Rian8337 requested changes

2021-02-13 10:10 UTC, Rian8337 commented on src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
> +        }
I think it is better if you check this when the game attaches these scenes for the first time, found here (`scorebar` needs to be done separately though).
https://github.com/osudroid/osu-droid/blob/2b192612bbf80557422ed9413e7e2519ed14aa50/src/ru/nsu/ccfit/zuev/osu/game/GameScene.java#L934-L942

And if you are not aware, `ScoreBar` would appear again if a break section in the beatmap exists (once the break section is over).
https://github.com/osudroid/osu-droid/blob/2b192612bbf80557422ed9413e7e2519ed14aa50/src/ru/nsu/ccfit/zuev/osu/game/GameScene.java#L1447-L1453

2021-02-17 00:51 UTC, Ycro-osu-catch commented
During Gameplay
In-Game Interface On / Off
as in osu desktop / pc?

2021-02-20 04:00 UTC, Rian8337 commented
I see you have committed the fix in your master branch (which I don't actually recommend, but oh well). You can either create a new pull request with the branch or continue to work on this pull request.

2021-02-23 17:24 UTC, closed without merging